### ISSUE TITLE
Same port of uvicorn

### ISSUE THREAD

**Issue by kadnan** [paurakhsharma/python-microservice-fastapi#5]
So both services are running on `uvicorn app.main:app --reload --host 0.0.0.0 --port 8000`?

**Comment by paurakhsharma** [comment]
Yes, they are but remember they are in a different container,
hence they can both run on the same port.

**Comment by kadnan** [comment]
I know that part but what if one wants to access Service A and Service B, what IP and Port will they get for both?

**Comment by kadnan** [comment]
nvm  I noticed different forwarded ports: ` - 8001:8000`
